In [1]:
import pandas as pd

In [6]:
df_attacking = pd.read_csv('raw_data/stats/attacking.csv')

In [7]:
df

,serial,player_name,club,position,assists,corner_taken,offsides,dribbles,match_played
0,1,Bruno Fernandes,Man. United,Midfielder,7,10,2,7,7
1,2,Vinícius Júnior,Real Madrid,Forward,6,3,4,83,13
2,2,Sané,Bayern,Midfielder,6,3,3,32,10
3,4,Antony,Ajax,Forward,5,3,4,28,7
4,5,Alexander-Arnold,Liverpool,Defender,4,36,0,9,9
...,...,...,...,...,...,...,...,...,...
171,64,Tolisso,Bayern,Midfielder,1,0,0,0,4
172,64,Schuurs,Ajax,Defender,1,0,0,0,3
173,64,Kryvtsov,Shakhtar Donetsk,Defender,1,0,0,0,3
174,64,Stanišić,Bayern,Defender,1,0,0,0,2
175,64,Bernardo,Salzburg,Defender,1,0,0,0,2

In [5]:
df.describe()

,serial,assists,corner_taken,offsides,dribbles,match_played
count,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000
mean,47.613636,1.596591,3.340909,1.420455,8.982955,6.988636
std,22.527916,1.042957,6.266257,2.246122,11.190034,2.563454
min,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,24.000000,1.000000,0.000000,0.000000,2.000000,5.000000
50%,64.000000,1.000000,0.000000,0.000000,5.000000,6.500000
75%,64.000000,2.000000,4.250000,2.000000,12.000000,8.000000
max,64.000000,7.000000,36.000000,10.000000,83.000000,13.000000

In [23]:
df_attempts = pd.read_csv('raw_data/stats/attempts.csv')
df_attempts

,serial,player_name,club,position,total_attempts,on_target,off_target,blocked,match_played
0,1,Benzema,Real Madrid,Forward,45,23,13,9,12
1,2,Salah,Liverpool,Forward,42,22,11,9,13
2,3,Mahrez,Man. City,Midfielder,37,18,8,11,12
3,4,Sané,Bayern,Midfielder,33,13,12,8,10
4,5,Lewandowski,Bayern,Forward,31,19,8,4,10
...,...,...,...,...,...,...,...,...,...
541,440,Dina Ebimbe,Paris,Midfielder,1,0,0,1,1
542,440,N'Koudou,Beşiktaş,Midfielder,1,0,0,1,1
543,440,Izquierdo,Club Brugge,Forward,1,0,0,1,1
544,440,Radonjić,Benfica,Forward,1,0,0,1,1
545,440,Agüero,Barcelona,Forward,1,0,0,1,1

In [9]:
df_defending = pd.read_csv('raw_data/stats/defending.csv')

In [22]:
df_disciplinary = pd.read_csv('raw_data/stats/disciplinary.csv')
df_disciplinary

,serial,player_name,club,position,fouls_committed,fouls_suffered,red,yellow,minutes_played,match_played
0,1,João Palhinha,Sporting CP,Midfielder,23,17,2,0,534,6
1,2,Capoue,Villarreal,Midfielder,19,17,3,1,1046,12
2,2,Rodri,Man. City,Midfielder,19,4,2,0,842,10
3,2,Seiwald,Salzburg,Midfielder,19,3,2,0,649,8
4,5,Balanta,Club Brugge,Midfielder,18,3,4,0,407,5
...,...,...,...,...,...,...,...,...,...,...
579,491,Eric Ramirez,Dynamo Kyiv,Forward,1,0,0,0,16,2
580,491,Bradarić,LOSC,Defender,1,0,0,0,13,1
581,491,Iborra,Villarreal,Midfielder,1,0,0,0,10,1
582,491,Zhegrova,LOSC,Midfielder,1,0,0,0,9,1
583,491,Chiellini,Juventus,Defender,1,0,0,0,7,1

In [32]:
df_distributon = pd.read_csv('raw_data/stats/distributon.csv')
df_distributon['position'].value_counts()

Midfielder    227
Defender      211
Forward       120
Goalkeeper     50
Name: position, dtype: int64

In [83]:
df_distributon

,serial,player_name,club,position,pass_accuracy,pass_attempted,pass_completed,cross_accuracy,cross_attempted,cross_complted,freekicks_taken,match_played
0,1,Erokhin,Zenit,Midfielder,98.0,27,26,0,2,0,0,6
1,2,Eric García,Barcelona,Defender,97.5,203,197,0,0,0,1,4
2,3,Ulreich,Bayern,Goalkeeper,97.0,32,31,0,0,0,1,1
3,4,Rugani,Juventus,Defender,96.8,130,122,0,0,0,0,4
4,5,J. Timber,Ajax,Midfielder,95.8,497,474,0,1,0,14,8
...,...,...,...,...,...,...,...,...,...,...,...,...
603,604,Phillips,Liverpool,Defender,44.5,37,33,0,0,0,1,2
604,605,Philipp,Wolfsburg,Forward,44.0,9,7,0,0,0,1,2
605,606,Brobbey,Leipzig,Forward,42.6,23,13,0,2,0,0,5
606,607,Traoré,Shakhtar Donetsk,Forward,36.5,22,16,0,0,0,0,2
607,608,Verbič,Dynamo Kyiv,Midfielder,35.7,26,18,0,0,0,0,3

In [59]:
df_distributon[df_distributon['position'] == 'Goalkeeper'].head()

,serial,player_name,club,position,pass_accuracy,pass_attempted,pass_completed,cross_accuracy,cross_attempted,cross_complted,freekicks_taken,match_played
2,3,Ulreich,Bayern,Goalkeeper,97.0,32,31,0,0,0,1,1
51,48,Steffen,Man. City,Goalkeeper,92.0,25,23,0,0,0,3,1
57,57,Handanovič,Inter,Goalkeeper,91.6,253,230,0,0,0,7,8
64,64,Pyatov,Shakhtar Donetsk,Goalkeeper,91.3,83,75,0,0,0,3,3
69,70,Neuer,Bayern,Goalkeeper,90.9,352,318,0,0,0,8,9

In [61]:
df_distributon['freekicks_taken']

0       0
1       1
2       1
3       0
4      14
       ..
603     1
604     1
605     0
606     0
607     0
Name: freekicks_taken, Length: 608, dtype: int64

In [28]:
df_goalkeeping = pd.read_csv('raw_data/stats/goalkeeping.csv')
df_goalkeeping

,serial,player_name,club,position,saved,conceded,saved_penalties,cleansheets,punches made,match_played
0,1,Courtois,Real Madrid,Goalkeeper,61,14,1,5,4,13
1,2,Rulli,Villarreal,Goalkeeper,41,16,0,3,12,12
2,3,Vlachodimos,Benfica,Goalkeeper,38,17,1,5,5,10
3,4,Athanasiadis,Sheriff,Goalkeeper,29,8,0,1,2,5
4,5,Mignolet,Club Brugge,Goalkeeper,28,20,0,0,1,6
5,6,Oblak,Atlético,Goalkeeper,26,10,0,3,2,10
6,7,Musso,Atalanta,Goalkeeper,21,13,0,1,1,6
7,8,Ersin Destanoğlu,Beşiktaş,Goalkeeper,20,17,0,0,0,5
8,9,De Gea,Man. United,Goalkeeper,19,9,0,1,0,7
9,9,Dahlin,Malmö,Goalkeeper,19,8,1,0,3,4
10,11,Diogo Costa,Porto,Goalkeeper,18,11,0,2,2,6
11,11,Trubin,Shakhtar Donetsk,Goalkeeper,18,9,0,0,0,3
12,11,Casteels,Wolfsburg,Goalkeeper,18,8,0,1,2,5
13,11,Donnarumma,Paris,Goalkeeper,18,6,1,2,9,5
14,15,Adán,Sporting CP,Goalkeeper,17,13,0,2,8,7
15,16,Köhn,Salzburg,Goalkeeper,16,14,0,1,3,8
16,16,Ter Stegen,Barcelona,Goalkeeper,16,9,0,3,2,6
17,18,Alisson Becker,Liverpool,Goalkeeper,15,14,0,4,3,13
18,19,Ederson,Man. City,Goalkeeper,14,14,0,4,1,11
19,19,Kobel,Dortmund,Goalkeeper,14,11,1,2,1,6
20,19,Szczęsny,Juventus,Goalkeeper,14,10,0,3,3,7
21,19,Maignan,Milan,Goalkeeper,14,7,1,0,1,3
22,19,Neuer,Bayern,Goalkeeper,14,6,0,4,1,9
23,19,Bounou,Sevilla,Goalkeeper,14,5,0,2,1,6
24,25,Bushchan,Dynamo Kyiv,Goalkeeper,13,11,0,0,4,5
25,25,Pasveer,Ajax,Goalkeeper,13,6,0,2,2,6
26,25,Diawara,Malmö,Goalkeeper,13,6,0,0,1,3
27,25,Grbić,LOSC,Goalkeeper,13,4,0,3,1,6
28,29,Handanovič,Inter,Goalkeeper,12,7,0,3,5,8
29,29,Kritsyuk,Zenit,Goalkeeper,12,6,0,1,10,4
30,29,Faivre,Young Boys,Goalkeeper,12,6,0,0,1,3
31,32,Gulácsi,Leipzig,Goalkeeper,11,14,0,0,0,5
32,32,Navas,Paris,Goalkeeper,11,5,0,0,3,3
33,34,Mendy,Chelsea,Goalkeeper,9,7,0,5,2,9
34,34,Von Ballmoos,Young Boys,Goalkeeper,9,6,0,0,1,3
35,36,Tătăruşanu,Milan,Goalkeeper,8,2,0,1,2,3
36,37,Celeadnic,Sheriff,Goalkeeper,6,3,0,0,1,1
37,38,M. Kerzhakov,Zenit,Goalkeeper,5,4,0,0,0,2
38,38,Pyatov,Shakhtar Donetsk,Goalkeeper,5,2,0,2,4,3
39,38,Pervan,Wolfsburg,Goalkeeper,5,2,0,0,0,1
40,41,Leo Jardim,LOSC,Goalkeeper,4,4,0,0,0,2
41,41,Kepa,Chelsea,Goalkeeper,4,3,0,0,0,1
42,41,Günok,Beşiktaş,Goalkeeper,4,2,0,0,0,1
43,41,Ulreich,Bayern,Goalkeeper,4,1,0,0,2,1
44,41,Boyko,Dynamo Kyiv,Goalkeeper,4,0,0,1,2,1
45,46,João Virginia,Sporting CP,Goalkeeper,3,4,0,0,0,1
46,46,Steffen,Man. City,Goalkeeper,3,2,0,0,1,1
47,46,Henderson,Man. United,Goalkeeper,3,1,0,0,1,1
48,46,Martínez,Leipzig,Goalkeeper,3,0,0,1,0,1
49,50,Onana,Ajax,Goalkeeper,2,2,0,0,0,2
50,50,Perin,Juventus,Goalkeeper,2,0,0,1,0,1
51,52,Shevchenko,Shakhtar Donetsk,Goalkeeper,1,1,0,0,0,1
52,52,Carson,Man. City,Goalkeeper,1,0,0,1,0,1

In [24]:
df_goals = pd.read_csv('raw_data/stats/goals.csv')
df_goals

,serial,player_name,club,position,goals,right_foot,left_foot,headers,others,inside_area,outside_areas,penalties,match_played
0,1,Benzema,Real Madrid,Forward,15,11,1,3,0,13,2,3,12
1,2,Lewandowski,Bayern,Forward,13,8,3,1,1,13,0,3,10
2,3,Haller,Ajax,Forward,11,3,4,3,1,11,0,1,8
3,4,Salah,Liverpool,Forward,8,0,8,0,0,7,1,1,13
4,5,Nkunku,Leipzig,Midfielder,7,3,1,3,0,7,0,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,73,Yansané,Sheriff,Forward,1,0,0,1,0,1,0,0,3
179,73,Yakhshiboev,Sheriff,Forward,1,0,0,1,0,1,0,0,3
180,73,Messias Junior,Milan,Forward,1,0,0,1,0,1,0,0,2
181,73,Morato,Benfica,Defender,1,0,0,1,0,1,0,0,2
182,73,Pedro Porro,Sporting CP,Defender,1,0,0,0,1,1,0,0,7

In [50]:
df_key_stats = pd.read_csv('raw_data/stats/key_stats.csv')
df_key_stats

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5
4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4
...,...,...,...,...,...,...,...,...
742,Gil Dias,Benfica,Midfielder,1,1,0,0,0.7
743,Rodrigo Ribeiro,Sporting CP,Forward,1,1,0,0,0.7
744,Cojocari,Sheriff,Defender,1,1,0,0,0.5
745,Maouassa,Club Brugge,Defender,1,1,0,0,0.2
746,Zesiger,Young Boys,Defender,1,1,0,0,-

In [15]:
df_key_stats.head()

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5
4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4

In [239]:
player_name = 'Courtois'

In [85]:
position = 'Goalkeeper'

## Retrieve position

## Goalkeeper

1. For a player_name and a goalkeeper position, get the statistics.
2. Put that in a function that takes as input the player name and the dataframes

In [240]:
saved_goalkeeper = round(df_goalkeeping[df_goalkeeping['player_name'] == player_name]['saved'].sum(),2)
saved_goalkeeper

61

In [241]:
conceded_goalkeeper = round(df_goalkeeping[df_goalkeeping['player_name'] == player_name]['conceded'].sum(),2)
conceded_goalkeeper

14

In [242]:
freekicks_taken_goalkeeper = round(df_distributon[df_distributon['player_name'] == player_name]['freekicks_taken'].sum(),2)
freekicks_taken_goalkeeper

27

In [243]:
saved_penalties_goalkeeper = round(df_goalkeeping[df_goalkeeping['player_name'] == player_name]['saved_penalties'].sum(),2)
saved_penalties_goalkeeper

1

In [244]:
cleansheets_goalkeeper = round(df_goalkeeping[df_goalkeeping['player_name'] == player_name]['cleansheets'].sum(),2)
cleansheets_goalkeeper

5

In [245]:
output_goalkeeper = {
    "Saved goals" : saved_goalkeeper, 
    "Conceded goals" : conceded_goalkeeper, 
    "Freekicks" : freekicks_taken_goalkeeper,
    "Saved penalties" : saved_penalties_goalkeeper,
    "Cleansheets" : cleansheets_goalkeeper}
output_goalkeeper

{'Saved goals': 61,
 'Conceded goals': 14,
 'Freekicks': 27,
 'Saved penalties': 1,
 'Cleansheets': 5}

In [246]:
def calculate_goalkeeper_kpis(player_name):
    return output_goalkeeper

In [247]:
calculate_goalkeeper_kpis('Courtois')

{'Saved goals': 61,
 'Conceded goals': 14,
 'Freekicks': 27,
 'Saved penalties': 1,
 'Cleansheets': 5}

## Forward

In [105]:
df_attempts.head()

,serial,player_name,club,position,total_attempts,on_target,off_target,blocked,match_played
0,1,Benzema,Real Madrid,Forward,45,23,13,9,12
1,2,Salah,Liverpool,Forward,42,22,11,9,13
2,3,Mahrez,Man. City,Midfielder,37,18,8,11,12
3,4,Sané,Bayern,Midfielder,33,13,12,8,10
4,5,Lewandowski,Bayern,Forward,31,19,8,4,10

In [136]:
df_attacking.head()

,serial,player_name,club,position,assists,corner_taken,offsides,dribbles,match_played
0,1,Bruno Fernandes,Man. United,Midfielder,7,10,2,7,7
1,2,Vinícius Júnior,Real Madrid,Forward,6,3,4,83,13
2,2,Sané,Bayern,Midfielder,6,3,3,32,10
3,4,Antony,Ajax,Forward,5,3,4,28,7
4,5,Alexander-Arnold,Liverpool,Defender,4,36,0,9,9

In [232]:
player_name = 'Benzema'

In [233]:
goals_forward = round(df_goals[df_goals['player_name'] == player_name]['goals'].sum(),2)
goals_forward

15

In [234]:
goals_forwardpergame = round(df_goals[df_goals['player_name'] == player_name]['goals'].sum() / df_attempts[df_attempts['player_name'] == player_name]['match_played'].sum(),2)
goals_forwardpergame

1.25

In [235]:
assists_forward = round(df_attacking[df_attacking['player_name'] == player_name]['assists'].sum(),2)
assists_forward

1

In [236]:
assists_forwardpergame = round(df_attacking[df_attacking['player_name'] == player_name]['assists'].sum() / df_attempts[df_attempts['player_name'] == player_name]['match_played'].sum(),2)
assists_forwardpergame

0.08

In [237]:
shots_on_target_forward = round(df_attempts[df_attempts['player_name'] == player_name]['on_target'].sum(),2)
shots_on_target_forward

23

In [227]:
shots_on_target_pergame_forward = round(df_attempts[df_attempts['player_name'] == player_name]['on_target'].sum() / df_attempts[df_attempts['player_name'] == player_name]['match_played'].sum(),2)
shots_on_target_pergame_forward

0.18

In [226]:
successful_dribbles_forward = round(df_attacking[df_attacking['player_name'] == player_name]['dribbles'].sum(),2)
successful_dribbles_forward

0

In [169]:
output_forward = {
    "Total goals" : goals_forward, 
    "Goals per game" : goals_forwardpergame,
    "Total assists" : assists_forward, 
    "Assists per game" : assists_forwardpergame,
    "Shots on target" : shots_on_target_forward,
    "Shots on target per game" : shots_on_target_pergame_forward,
    "Successful dribbles" : successful_dribbles_forward}
output_forward

{'Total goals': 15,
 'Goals per game': 1.25,
 'Total assists': 1,
 'Assists per game': 0.4,
 'Shots on target': 7,
 'Shots on target per game': 0.7,
 'Successful dribbles': 14}

In [170]:
def calculate_forward_kpis(player_name):
    return output_forward

In [171]:
calculate_forward_kpis('Benzema')

{'Total goals': 15,
 'Goals per game': 1.25,
 'Total assists': 1,
 'Assists per game': 0.4,
 'Shots on target': 7,
 'Shots on target per game': 0.7,
 'Successful dribbles': 14}

## Midfielder

In [148]:
player_name = 'De Bruyne'

In [149]:
df_distributon.head()

,serial,player_name,club,position,pass_accuracy,pass_attempted,pass_completed,cross_accuracy,cross_attempted,cross_complted,freekicks_taken,match_played
0,1,Erokhin,Zenit,Midfielder,98.0,27,26,0,2,0,0,6
1,2,Eric García,Barcelona,Defender,97.5,203,197,0,0,0,1,4
2,3,Ulreich,Bayern,Goalkeeper,97.0,32,31,0,0,0,1,1
3,4,Rugani,Juventus,Defender,96.8,130,122,0,0,0,0,4
4,5,J. Timber,Ajax,Midfielder,95.8,497,474,0,1,0,14,8

In [151]:
df_distributon[df_distributon['player_name']== player_name]

,serial,player_name,club,position,pass_accuracy,pass_attempted,pass_completed,cross_accuracy,cross_attempted,cross_complted,freekicks_taken,match_played
317,318,De Bruyne,Man. City,Midfielder,82.6,397,334,26,41,11,18,10

In [152]:
df_defending[df_defending['player_name']== player_name]

,serial,player_name,club,position,balls_recoverd,tackles,t_won,t_lost,clearance_attempted,match_played
319,317,De Bruyne,Man. City,Midfielder,11,6,0,6,2,10

In [159]:
df_disciplinary.head()

,serial,player_name,club,position,fouls_committed,fouls_suffered,red,yellow,minutes_played,match_played
0,1,João Palhinha,Sporting CP,Midfielder,23,17,2,0,534,6
1,2,Capoue,Villarreal,Midfielder,19,17,3,1,1046,12
2,2,Rodri,Man. City,Midfielder,19,4,2,0,842,10
3,2,Seiwald,Salzburg,Midfielder,19,3,2,0,649,8
4,5,Balanta,Club Brugge,Midfielder,18,3,4,0,407,5

In [225]:
ball_recoveries_midfielder = round(df_defending[df_defending['player_name'] == player_name]['balls_recoverd'].sum() / df_defending[df_defending['player_name'] == player_name]['match_played'].sum(),2)
ball_recoveries_midfielder

6.91

In [224]:
pass_accuracy_midfielder = round(df_distributon[df_distributon['player_name'] == player_name]['pass_accuracy'].mean(),2)
pass_accuracy_midfielder

89.1

In [223]:
total_assists_midfielder = round(df_attacking[df_attacking['player_name'] == player_name]['assists'].sum(),2)
total_assists_midfielder

0

In [222]:
key_passes_pergame_midfielder = round(total_assists_midfielder / df_attacking[df_attacking['player_name'] == player_name]['match_played'].sum(),2)
key_passes_pergame_midfielder

/var/folders/f8/1263218d3v7b0d83vf4w0n2h0000gn/T/ipykernel_86819/1649228846.py:1: RuntimeWarning: divide by zero encountered in long_scalars
  key_passes_pergame_midfielder = round(total_assists_midfielder / df_attacking[df_attacking['player_name'] == player_name]['match_played'].sum(),2)

inf

In [221]:
output_midfielder = {
    'Total assists': total_assists_midfielder,
    'Ball Recoveries per Game': ball_recoveries_midfielder,
    'Pass Accuracy': pass_accuracy_midfielder,
    'Key passes per game': key_passes_pergame_midfielder,
    }
output_midfielder

{'Total assists': 4,
 'Ball Recoveries per Game': 6.909090909090909,
 'Pass Accuracy': 82.6,
 'Key passes per game': inf}

In [184]:
def calculate_midfielder_kpis(player_name):
    return output_midfielder

In [185]:
calculate_midfielder_kpis('De Bruyne')

{'Total assists': 4,
 'Ball Recoveries per Game': 1.1,
 'Pass Accuracy': 82.6,
 'Key passes per game': 0.4}

## Defender

In [199]:
player_name = 'Casemiro'

In [192]:
df_defending.head()

,serial,player_name,club,position,balls_recoverd,tackles,t_won,t_lost,clearance_attempted,match_played
0,1,Casemiro,Real Madrid,Midfielder,76,31,13,18,19,11
1,1,Éder Militão,Real Madrid,Defender,76,19,6,13,32,12
2,1,Reinildo,Atlético,Defender,76,13,6,7,20,10
3,4,Fabinho,Liverpool,Midfielder,74,23,9,14,8,13
4,5,Albiol,Villarreal,Defender,73,9,6,3,62,12

In [220]:
tackles_won_defender = round(df_defending[df_defending['player_name'] == player_name]['t_won'].sum(),2)
tackles_won_defender

13

In [217]:
tackles_won_pergame_defender = round(df_defending[df_defending['player_name'] == player_name]['t_won'].sum() / df_defending[df_defending['player_name'] == player_name]['match_played'].sum(),2)
tackles_won_pergame_defender

1.18

In [219]:
fouls_pergame_defender = round(df_disciplinary[df_disciplinary['player_name'] == player_name]['fouls_committed'].sum() / games_played,2)
fouls_pergame_defender

17.0

In [218]:
output_defender = {
        'Tackles Won' : tackles_won_defender,
        'Tackles Won per Game': tackles_won_pergame_defender,
        'Fouls Committed per Game': fouls_pergame_defender,
    }
output_defender

{'Tackles Won': 13,
 'Tackles Won per Game': 1.18,
 'Fouls Committed per Game': 17.0}

In [ ]:
def calculate_defender_kpis(player_name):
    return output_defender

## General

In [209]:
red_yellow_cards_total = df_disciplinary[df_disciplinary['player_name'] == player_name][['red', 'yellow']].sum().to_dict()
red_yellow_cards_total

{'red': 3, 'yellow': 0}

In [211]:
df_disciplinary[df_disciplinary['player_name'] == player_name]

,serial,player_name,club,position,fouls_committed,fouls_suffered,red,yellow,minutes_played,match_played
5,6,Casemiro,Real Madrid,Midfielder,17,18,3,0,914,11